/*
 *
 * MyPage constants
 *
 */

export const MYPAGE_REVIEWS_ACTION = 'app/MyPage/MYPAGE_REVIEW_ACTION';
export const MYPAGE_REVIEWS_SUCCESS = 'app/MyPage/MYPAGE_REVIEW_SUCCESS';
export const MYPAGE_REVIEWS_FAILURE = 'app/MyPage/MYPAGE_REVIEW_FAILURE';
export const MYPAGE_REWORDS_ACTION = 'app/MyPage/MYPAGE_REWORD_ACTION';
export const MYPAGE_REWORDS_SUCCESS = 'app/MyPage/MYPAGE_REWORD_SUCCESS';
export const MYPAGE_REWORDS_FAILURE = 'app/MyPage/MYPAGE_REWORD_FAILURE';
export const REWORDS_ACQUIRE_ACTION = 'app/MyPage/REWORDS_ACQUIRE_ACTION';
export const REWORDS_ACQUIRE_SUCCESS = 'app/MyPage/REWORDS_ACQUIRE_SUCCESS';
export const REWORDS_ACQUIRE_FAILURE = 'app/MyPage/REWORDS_ACQUIRE_FAILURE';
export const FOLLOWER_COUNT_ACTION = 'app/MyPage/FOLLOWER_COUNT_ACTION';
export const FOLLOWER_COUNT_SUCCESS = 'app/MyPage/FOLLOWER_COUNT_SUCCESS';
export const FOLLOWER_COUNT_FAILURE = 'app/MyPage/FOLLOWER_COUNT_FAILURE';
export const FOLLOWING_COUNT_ACTION = 'app/MyPage/FOLLOWING_COUNT_ACTION';
export const FOLLOWING_COUNT_SUCCESS = 'app/MyPage/FOLLOWING_COUNT_SUCCESS';
export const FOLLOWING_COUNT_FAILURE = 'app/MyPage/FOLLOWING_COUNT_FAILURE';
export const LOAD_USER_DATA = 'app/MyPage/LOAD_USER_DATA';
export const LOAD_USER_SUCCESS = 'app/MyPage/LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'app/MyPage/LOAD_USER_ERROR';
