/*
 *
 * MyPage constants
 *
 */

export const MYPAGE_ACTION = 'app/MyPage/MYPAGE_ACTION';
export const MYPAGE_SUCCESS = 'app/MyPage/MYPAGE_SUCCESS';
export const MYPAGE_FAILURE = 'app/MyPage/MYPAGE_FAILURE';
export const FOLLOWER_COUNT_ACTION = 'app/MyPage/FOLLOWER_COUNT_ACTION';
export const FOLLOWER_COUNT_SUCCESS = 'app/MyPage/FOLLOWER_COUNT_SUCCESS';
export const FOLLOWER_COUNT_FAILURE = 'app/MyPage/FOLLOWER_COUNT_FAILURE';
export const FOLLOWING_COUNT_ACTION = 'app/MyPage/FOLLOWING_COUNT_ACTION';
export const FOLLOWING_COUNT_SUCCESS = 'app/MyPage/FOLLOWING_COUNT_SUCCESS';
export const FOLLOWING_COUNT_FAILURE = 'app/MyPage/FOLLOWING_COUNT_FAILURE';
export const LOAD_USER_DATA = 'app/MyPage/LOAD_USER_DATA';
export const LOAD_USER_SUCCESS = 'app/MyPage/LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'app/MyPage/LOAD_USER_ERROR';
